{
 "title": "Wi-Fi Ninja",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "WLC metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data - IN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"inBytes\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "Data - OUT",
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"outBytes\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 0",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 2, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_0\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 1",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_1\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 2",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_2\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 3",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 14, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_3\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 4",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_4\")\n  |> yield()"
      }
     ]
    }
   ]
  },
  { "title": "Client metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"connectedClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n\n    \n    \n"
    }
   ]
  },
  {
   "title": "Client States",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Client Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wi-Fi_6_(6GHz)\" or r[\"_field\"] == \"Wi-Fi_6_(5GHz)\" or r[\"_field\"] == \"Wi-Fi_6_(2.4GHz)\" or r[\"_field\"] == \"Wi-Fi_5\" or r[\"_field\"] == \"Wi-Fi_4_(5GHz)\" or r[\"_field\"] == \"Wi-Fi_4_(2.4GHz)\" or r[\"_field\"] == \"Wi-Fi_3\" or r[\"_field\"] == \"Wi-Fi_2\" or r[\"_field\"] == \"Wi-Fi_1\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Clients - Site Tag (North)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\" or r[\"_measurement\"] == \"rf6ghz\" or r[\"_measurement\"] == \"rf2ghz\")\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\n  |> filter(fn: (r) => r[\"siteTag\"] == \"NorthSiteTag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"radioStas\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Clients - Site Tag (South)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\" or r[\"_measurement\"] == \"rf6ghz\" or r[\"_measurement\"] == \"rf2ghz\")\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\n  |> filter(fn: (r) => r[\"siteTag\"] == \"SouthSiteTag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"radioStas\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Clients - Site Tag (East)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\" or r[\"_measurement\"] == \"rf6ghz\" or r[\"_measurement\"] == \"rf2ghz\")\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\" and r[\"radioState\"] == \"radio-up\")\n  |> filter(fn: (r) => r[\"siteTag\"] == \"EastSiteTag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"radioStas\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Clients - Site Tag (West)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\" or r[\"_measurement\"] == \"rf6ghz\" or r[\"_measurement\"] == \"rf2ghz\")\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\n  |> filter(fn: (r) => r[\"siteTag\"] == \"WestSiteTag\")\n  |> filter(fn: (r) => r[\"_field\"] == \"radioStas\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "AP metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "Channel Changes - 2 GHz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf2ghz\")\r\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"radioChanges\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Channel Changes - 5 GHz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\")\r\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"radioChanges\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Channel Changes - 6 GHz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf6ghz\")\r\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"radioChanges\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Channel Utilization - 5GHz",
   "type": "heatmap",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\")\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\n  |> filter(fn: (r) => r[\"radioState\"] == \"radio-up\")\n  |> filter(fn: (r) => r[\"_field\"] == \"radioUtil\")\n  |> yield()"
    }
   ]
  }
 ]
}